### ISSUE TITLE
z-index on title is set to 1000!important

### ISSUE THREAD

**Issue by JamesLMilner** [dojo/parade#35]
The title bar is set to `z-index: 1000!important` which causes the SidePane widget to be underlayed beneath it. Is there a reason this is set so high? The class is also call z-100 which leads me to think maybe this was a typo?

line in question:
https://github.com/dojo/parade/blob/3c8222a6622e40f8dd2169c28892c81d4e6d421f/src/main.css#L20

![Screenshot_20200110_183308](https://user-images.githubusercontent.com/8822075/72176992-a821e400-33d7-11ea-85b1-5ccc7e51970e.png)

**Comment by matt-gadd** [comment]
No it was deliberate, otherwise things such as the menu pop over the header which we don't want. in reality i don't think the slidepane or other things should be popping out of a context, but that probably won't be fixed until we move the actual examples to an iframe.

**Comment by matt-gadd** [comment]
@JamesLMilner i've added an issue for the above here: https://github.com/dojo/parade/issues/37
