### ISSUE TITLE
Document widget properties to include properties from middleware and mixins

### ISSUE THREAD

**Issue by agubler** [dojo/parade#48]
At the moment widget properties are documented using a convention to find the properties interface. This means that expected properties that are decorated by middleware of mixins need to explicitly added to the widget properties by extending the appropriate interfaces.

We need to change parade to be able to determine the "complete" widget properties interface without needing to use extends each or the interfaces.

**Comment by matt-gadd** [comment]
I believe we can probably copy/leverage a lot of the code out the element-transformer for this: https://github.com/dojo/webpack-contrib/blob/master/src/element-transformer/ElementTransformer.ts
