### ISSUE TITLE
Feature Request : Keys

### ISSUE THREAD

**Issue by sebilasse** [dojo/parade#62]
Hello,

a quick feature request for this fantastic thing.

User story : 
People want to extend widgets with own CSS declarations.
They need to know which `key`s for which nodes are present for "extra classes" …

Currently parade shows tables for e.g. `Properties`, `Children`, `Theme` –
how about "Keys" ?

**Comment by agubler** [comment]
@sebilasse what do you mean "keys"? The keys that can be used by `extraClasses` are the same as the CSS class names in the theme table.
