### ISSUE TITLE
Routes should set page title

### ISSUE THREAD

**Issue by aciccarello** [dojo/parade#76]
The routes should define page titles so the tab title and browser history don't say "examples" on every page.

![Browser history list](https://user-images.githubusercontent.com/11273838/110548657-c079b580-80e5-11eb-8fd0-a991852bc495.png)

**Comment by bitpshr** [comment]
+1, proper titles FTW.

**Comment by agubler** [comment]
This can be done using the `setDocumentTitle` option when configuring the router in parade, something like:

```tsx
		registerRouterInjector(routes, registry, {
			setDocumentTitle: ({params}) => {
				return `Dojo Parade - ${params.widget}`;
			}
		});
```
